# CHAPTER 4: NumPy Basics: Arrays and Vectorized Computation

### Book: Python For Data Analysis

### Notebook Author: Muhammad Hamad

### Introduction
NumPy, short for Numerical Python

ndarray, a fast and space-efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities

• Standard mathematical functions for fast operations on entire arrays of data without having to write loops

• Tools for reading / writing array data to disk and working with memory-mapped files

• Linear algebra, random number generation, and Fourier transform capabilities

• Tools for integrating code written in C, C++, and Fortran

### For most data analysis applications, the main areas of functionality I’ll focus on are:

• Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations

• Common array algorithms like sorting, unique, and set operations

• Efficient descriptive statistics and aggregating/summarizing data

• Data alignment and relational data manipulations for merging and joining together heterogeneous data sets

• Expressing conditional logic as array expressions instead of loops with if-elifelse branches

• Group-wise data manipulations (aggregation, transformation, function application)

## Topic 1: The NumPy ndarray: A Multidimensional Array Object

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array

#### Task 1: Creating an nd array

In [2]:
import numpy as np
one_d=[5,2.7,9,68,23.58]
two_d=[[2,5,6,9,8],[8,5,6,5,2]]

np_one_d=np.array(one_d)
np_two_d=np.array(two_d)


In [3]:
#One Dimensional array
print(np_one_d)

[ 5.    2.7   9.   68.   23.58]


In [4]:
#Two Dimensional array
print(np_two_d)

[[2 5 6 9 8]
 [8 5 6 5 2]]


In [5]:
# No. of rows and columns in an array
print(np_one_d.shape)
print(np_two_d.shape)

(5,)
(2, 5)


In [6]:
# type of array 
print(np_one_d.dtype)
print(np_two_d.dtype)

float64
int32


In [7]:
# Dimension of array 
print(np_one_d.ndim)
print(np_two_d.ndim)

1
2


#### Task 2:  zeroed, ones and empty array

In [8]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [9]:
#focus on double paranthesis inside zeros
print(np.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Empty creates an array without initializing its values to any particular value.it will return uninitialized garbage

print(np.empty((3,3)))

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.53353523e-321]
 [1.45144512e-311 1.45144512e-311 0.00000000e+000]]


#### Task 3 : 
creates a sequential array
np.arange(start=1, stop=10, step=3)

In [11]:
arange=np.arange(10)

In [12]:
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(start=1, stop=10, step=3))

[1 4 7]


### Operations between Arrays and Scalars


In [14]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
arr2=np.array([[3,2,1],[6,5,4]])
print(arr2)

[[3 2 1]
 [6 5 4]]


In [16]:
# Element by Elemnt Multiplication
print(arr1*arr2)

[[ 3  4  3]
 [24 25 24]]


In [17]:
# colums of first matrix should be equal to rows of second matrix
print(arr1@arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [19]:
arr3=np.array([[2,4],[5,6]])
arr3

array([[2, 4],
       [5, 6]])

In [22]:
arr2.shape

(2, 3)

In [21]:
arr3.shape

(2, 2)

In [23]:
# colums of first matrix should be equal to rows of second matrix
print(arr2@arr3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)