# CHAPTER 4: NumPy Basics: Arrays and Vectorized Computation

### Book: Python For Data Analysis

### Notebook Author: Muhammad Hamad

### Introduction
NumPy, short for Numerical Python

ndarray, a fast and space-efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities

• Standard mathematical functions for fast operations on entire arrays of data without having to write loops

• Tools for reading / writing array data to disk and working with memory-mapped files

• Linear algebra, random number generation, and Fourier transform capabilities

• Tools for integrating code written in C, C++, and Fortran

### For most data analysis applications, the main areas of functionality I’ll focus on are:

• Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations

• Common array algorithms like sorting, unique, and set operations

• Efficient descriptive statistics and aggregating/summarizing data

• Data alignment and relational data manipulations for merging and joining together heterogeneous data sets

• Expressing conditional logic as array expressions instead of loops with if-elifelse branches

• Group-wise data manipulations (aggregation, transformation, function application)

## Topic 1: The NumPy ndarray: A Multidimensional Array Object

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array

#### Task 1: Creating an nd array

In [16]:
import numpy as np
one_d=[5,2.7,9,68,23.58]
two_d=[[2,5,6,9,8],[8,5,6,5,2]]

np_one_d=np.array(one_d)
np_two_d=np.array(two_d)


In [14]:
#One Dimensional array
print(np_one_d)

[ 5.    2.7   9.   68.   23.58]


In [19]:
#Two Dimensional array
print(np_two_d)

[[2 5 6 9 8]
 [8 5 6 5 2]]


In [22]:
# No. of rows and columns in an array
print(np_one_d.shape)
print(np_two_d.shape)

(5,)
(2, 5)


In [23]:
# type of array 
print(np_one_d.dtype)
print(np_two_d.dtype)

float64
int32


In [24]:
# Dimension of array 
print(np_one_d.ndim)
print(np_two_d.ndim)

1
2


#### Task 2:  zeroed, ones and empty array

In [27]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [30]:
#focus on double paranthesis inside zeros
print(np.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# Empty creates an array without initializing its values to any particular value.it will return uninitialized garbage

print(np.empty((3,3)))

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.05525742e-321]
 [1.33261336e-311 1.33261336e-311 1.29061685e-306]]
